### ISSUE TITLE
stacking route annotations

### ISSUE THREAD

**Issue by chriamue** [briancappello/flask-unchained#10]
Hi, a single route annotation works, tried both,
but stacking route annotations, only first works.
```
    @route('/list/<string:project>/', defaults={'req_path': ''})
    @route('/list/<string:project>/<path:req_path>')
    def image_listing(self, project, req_path):
...
```

**Comment by briancappello** [comment]
This should work, as long as you give each route a unique endpoint name. 

Reading more about this, in the upstream docs it suggests what you're doing should be working. Personally, that syntax not only looks awful but is also quite un-intuitive. I would much rather have end-user code be able to write this:
```
@route('/whatever/<string:param>/', defaults=dict(param='value'))
```
And then behind the scenes, we do what needs to be done for it to work with Werkzeug (namely, registering two routes with Flask). I *think* that code should end up living in `RegisterRoutesHook.process_objects`, if you want to play around with it (See the `hooks` module of the controller bundle). I'm happy to take a stab at it later too, this is getting a bit deep into the weeds of the implementation.

**Comment by briancappello** [comment]
@chriamue I just pushed a fix to master that hopefully implements support for multiple routes with the same endpoint name on view functions/methods. Can you give it a shot? I didn't add any magic (yet) so for now, you need to continue using the multiple routes (one with default parameter, the other with the parameter as part of the url rule)

**Comment by briancappello** [comment]
Hrm yep, not sure how I didn't run into that before... anyway, [fix](https://github.com/briancappello/flask-unchained/commit/9337c7ebe633434547a84f99a41f8fe144ce3637) pushed to master

**Comment by chriamue** [comment]
Works now, thank you for that.
