### ISSUE TITLE
Where would you put plain python classes?

### ISSUE THREAD

**Issue by squarism** [briancappello/flask-unchained#16]
Let's say you had an API endpoint somewhere.  You want to keep some logic out of the view, but you also need to have some method/functionality.  For example's sake, it's some generic thing like reversing a list.  Some projects might be tempted to make a `utils` package and start dumping code into that.  I try to delay that as much as I can because it turns out to be a junk drawer.  Since Flask-Unchained is slightly opinionated (not pejorative - I prefer this in a framework), where would you put plain old python classes?

Answering my own question, here are some thoughts or suggestions:
- `helpers/` - It's too close to utils.  Everything should be helping.  Eh.  I usually have formatters for views or something near something else for this
- `models/` - Is sqlalchemy.  Reversing a list doesn't touch the database.  The name is very close and a model doesn't have to touch the database.  In this case, a list doesn't _really_ contain data.  A User / Person / Employee / Product / Comment is a model.
- `lib/` - Is more of a C/C++ convention, I don't hate it though.
- `services/` - I'd consider this hitting the network.  A network service.  The term is overused.  FormObjects are sometimes called services.
- `utils/` - The default.  Turns into a junk drawer.
- `list/` - Naming it after the business case, the domain is not how Flask-Unchained is organized.  It's organized by technical types.
- `decorators/` - I like this for views, same as FormObjects.
- `presenters/` - Now we're just doing synonyms here.  I like this for this example because I'm probably reversing a list for a table maybe?  My made up example isn't real.

Maybe the hangup on presents answers the question.  I should think more about why I'm reversing a list.  If it's on the backend to the database, put it in there.  If it's on the backend talking to a service, put it in services.  If it's going to the frontend for the view, put it in helpers.  If it is so general that it is used by everything, put it in utils?

Naming stuff is hard.  🌻

**Comment by briancappello** [comment]
Heh naming is indeed tough :)

Something like your example would be considered a "service" in Flask Unchained. The term itself, service, I'd agree is definitely overused / overloaded. I use it as more or less anything that would be considered shared (reusable) functionality. (Anything you might want to use in more than one view, or even in other services.)

For example, I use the term `ModelManager` for a class that encapsulates all of the querying and manipulation logic around individual database models. Managers are a subclass of `Service`, which is what allows them to automatically be injected into views and other services.

```python
from flask_unchained import Controller, Service, injectable  # assuming you're on @master

class ListService(Service):
    def reverse(self, items):
        return reversed(items)

class SiteController(Controller):
    list_service: ListService = injectable

    def index(self):
        self.list_service.reverse(some_list)
```

By default services are loaded from the `services` module/package within each of your bundles. But they can live in multiple places (assuming you're on `@master`):

```python
class YourBundle(Bundle):
    services_module_names = ['services', 'managers']
```

That would correspond to a folder structure like so:

```
/your_bundle/
  __init__.py  # where the YourBundle class lives
  services.py  # it works with modules
  managers/  # or with packages
    __init__.py
```

In this way, you can rename and organize stuff however you like :)
