### ISSUE TITLE
[BUG] Admin bundle points to security.login, but Security bundle defines security_controller.login

### ISSUE THREAD

**Issue by nielslerches** [briancappello/flask-unchained#19]
First of, I just want to say thank you for making this package. This is exactly what I need for a project I'm doing.

Anyways, the issue at hand:

The login and logout endpoints specified in the Admin bundle config seems to point to an endpoint in the Security bundle which doesn't exist in the current commit.

i.e. `ADMIN_LOGOUT_ENDPOINT = "security.logout"` https://github.com/briancappello/flask-unchained/blob/23b824c113aaf4f9ec4c7800983ead3785dfa233/flask_unchained/bundles/admin/config.py#L61

My workaround is just to set this variable in my project config to `ADMIN_LOGOUT_ENDPOINT = "security_controller.logout"`

I think a better solution would be to either set the config variable in the Admin bundle itself to `"security_controller.<endpoint>"`, or edit the references in the Security bundle to `"security.<endpoint>"`. I don't have a personal opinion on which option is better. Maybe there's even a better solution.

I can make a PR either way, if needed.

Attached is a screenshot of the werkzeug routing error I encounter when trying to access /admin/.

![Screenshot from 2021-01-16 10-33-24](https://user-images.githubusercontent.com/29734775/104808409-6267da80-57e6-11eb-8c25-536534f9090a.png)

**Comment by briancappello** [comment]
Hi @nielslerches, thanks for the report! I think this is maybe both a bug and a case of missing documentation :)

The Admin Bundle includes its own `AdminSecurityController` - which is the same as the regular `SecurityController`, except it is configured to use admin-specific templates. This should be included in your declarative routes like so:

```python
# your-project/your_app_bundle/routes.py

from flask_unchained import (controller, resource, func, include, prefix,
                                get, delete, post, patch, put, rule)

routes = lambda: [
  # ...
  include('flask_unchained.bundles.admin.routes'),
]
```

And then, if you take a look at `flask_unchained/bundles/admin/routes.py`, the endpoint names must also be configured to match:

```python
# your-project/your_app_bundle/config.py
from flask_unchained import BundleConfig

class Config(BundleConfig):
  ADMIN_LOGIN_ENDPOINT = 'admin.login'
  ADMIN_LOGOUT_ENDPOINT = 'admin.logout'
```

Hopefully that gets it working as expected?

**Comment by nielslerches** [comment]
Yes, this solves the problem :)

**Comment by briancappello** [comment]
Hi @nielslerches, I've just pushed a new release, `v0.8.1`, that fixes this and a few other bugs I discovered playing around with the Admin Bundle. It also adds a couple new features, for example better integrating the Security Bundle with the Admin interface by adding `ModelAdmin`s for the `User` and `Role` classes. Apologies for the delay in getting this pushed and please do let me know if you encounter any other issues and/or have any questions - I'll do my best to answer them as quickly as I can! Thanks again :)
